name: goog-api-client
version: 0.1.0.0
github: "JunKikuchi/goog-api-client"
license: BSD3
author: "Jun Kikuchi"
maintainer: "kikuchi@bonnou.com"
copyright: "2020 Jun Kikuchi"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/JunKikuchi/goog-api-client#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  goog-api-client-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - goog-api-client

tests:
  goog-api-client-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - goog-api-client
